CREATE TABLE IF NOT EXISTS `Livros` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`Autor` LONGTEXT NULL,
	`DataLancamento` DATETIME(6) NOT NULL,
	`Preco` DECIMAL(65,2) NOT NULL,
	`Titulo` LONGTEXT NULL,
	PRIMARY KEY (`Id`)
)
ENGINE=InnoDB
;