CREATE TABLE IF NOT EXISTS `Pessoas` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(50) NULL DEFAULT NULL,
	`Sobrenome` VARCHAR(50) NULL DEFAULT NULL,
	`Endereco` VARCHAR(50) NULL DEFAULT NULL,
	`Genero` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;